-- +goose Up
ALTER TABLE dags ADD COLUMN IF NOT EXISTS public          BOOLEAN  NOT NULL DEFAULT FALSE;
ALTER TABLE dags ADD COLUMN IF NOT EXISTS embed_revision  BIGINT   NOT NULL DEFAULT 0;

-- +goose Down
ALTER TABLE dags DROP COLUMN IF EXISTS public;
ALTER TABLE dags DROP COLUMN IF EXISTS embed_revision;
